name: rAPId Integration Tests

on:
  push:
    branches:
      - "feature/en-69/rapid-ui-integration-tests"

  workflow_dispatch:

jobs:

  run-ui-test:
    runs-on: self-hosted
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Log commit SHA
        run: echo $GITHUB_SHA

      - name: Populate .env with additional vars
        run: |
          cp ./.github/.github.env .env

      - name: Install packages
        run: make npm-setup

      - name: Install playwright browsers
        run: npx playwright install-deps && npx playwright install

#      - name: Install playwright browsers
#        run: npm install -D @playwright/test

      - name: start rapid-ui
        run: npx playwright test ./ui-test/ui-test.spec.ts

#     - name: make install
#        run: apt update && apt install -y make