name: rAPId Integration Tests

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:

  run-ui-test:
    runs-on: self-hosted
    env:
      RAPID_UI_PASSWORD: ${{ secrets.RAPID_UI_PASSWORD }}
      RAPID_UI_USERNAME: ${{ secrets.RAPID_UI_USERNAME }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install packages
        run: make npm-setup

      - name: Install playwright browsers
        run: npx playwright install-deps && npx playwright install

      - name: run playwright tests
        run: npx playwright test ./ui-test/ui-test-full.spec.ts
